[deploy]
bucket = 'cfn-artifacts-newname'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'


[parameters]
EnvFrontendUrl = 'https://mohammedfirdous.works'
EnvBackendUrl = 'https://api.mohammedfirdous.works'
